apiVersion: v1
kind: ServiceAccount
metadata:
  name: echo-service
  annotations:
    mia-platform.eu/version: 14.3.1
  labels:
    app.kubernetes.io/part-of: github-app-v6
    app.kubernetes.io/managed-by: mia-platform
    mia-platform.eu/stage: DEV
    mia-platform.eu/tenant: rocket-playground
